import type { GiftCardType } from './types';

export const giftCards: GiftCardType[] = [
  // Amazon
  {
    id: '1',
    platform: 'Amazon',
    name: 'Amazon Gift Card',
    value: 100,
    imageUrl: 'https://placehold.co/600x400/ff9900/000000',
    instructions: `1. Visit www.amazon.in/redeem\n2. Enter the claim code and click "Apply to Your Balance".\n3. The gift card funds will be added to your account.`,
    category: 'Gift Card',
  },
  {
    id: '4',
    platform: 'Amazon',
    name: 'Amazon Gift Card',
    value: 250,
    imageUrl: 'https://placehold.co/600x400/ff9900/000000',
    instructions: `1. Visit www.amazon.in/redeem\n2. Enter the claim code and click "Apply to Your Balance".\n3. The gift card funds will be added to your account.`,
    category: 'Gift Card',
  },
  {
    id: '7',
    platform: 'Amazon',
    name: 'Amazon Gift Card',
    value: 500,
    imageUrl: 'https://placehold.co/600x400/ff9900/000000',
    instructions: `1. Visit www.amazon.in/redeem\n2. Enter the claim code and click "Apply to Your Balance".\n3. The gift card funds will be added to your account.`,
    category: 'Gift Card',
  },
  {
    id: '13',
    platform: 'Amazon',
    name: 'Amazon Gift Card',
    value: 1000,
    imageUrl: 'https://placehold.co/600x400/ff9900/000000',
    instructions: `1. Visit www.amazon.in/redeem\n2. Enter the claim code and click "Apply to Your Balance".\n3. The gift card funds will be added to your account.`,
    category: 'Gift Card',
  },

  // Steam
  {
    id: '2',
    platform: 'Steam',
    name: 'Steam Wallet Code',
    value: 250,
    imageUrl: 'https://placehold.co/600x400/1b2838/ffffff',
    instructions: `1. Go to store.steampowered.com/account/redeemwalletcode\n2. Sign in to your Steam account.\n3. Enter your Wallet Code and click "Continue".`,
    category: 'Gift Card',
  },
  {
    id: '5',
    platform: 'Steam',
    name: 'Steam Wallet Code',
    value: 500,
    imageUrl: 'https://placehold.co/600x400/1b2838/ffffff',
    instructions: `1. Go to store.steampowered.com/account/redeemwalletcode\n2. Sign in to your Steam account.\n3. Enter your Wallet Code and click "Continue".`,
    category: 'Gift Card',
  },
  {
    id: '8',
    platform: 'Steam',
    name: 'Steam Wallet Code',
    value: 1000,
    imageUrl: 'https://placehold.co/600x400/1b2838/ffffff',
    instructions: `1. Go to store.steampowered.com/account/redeemwalletcode\n2. Sign in to your Steam account.\n3. Enter your Wallet Code and click "Continue".`,
    category: 'Gift Card',
  },
  {
    id: '14',
    platform: 'Steam',
    name: 'Steam Wallet Code',
    value: 1500,
    imageUrl: 'https://placehold.co/600x400/1b2838/ffffff',
    instructions: `1. Go to store.steampowered.com/account/redeemwalletcode\n2. Sign in to your Steam account.\n3. Enter your Wallet Code and click "Continue".`,
    category: 'Gift Card',
  },

  // Google Play
  {
    id: '3',
    platform: 'Google Play',
    name: 'Google Play Gift Code',
    value: 100,
    imageUrl: 'https://placehold.co/600x400/3ddc84/ffffff',
    instructions: `1. Open the Google Play Store app.\n2. Tap Menu > Redeem.\n3. Enter your code.\n4. Tap "Redeem".`,
    category: 'Gift Card',
  },
  {
    id: '6',
    platform: 'Google Play',
    name: 'Google Play Gift Code',
    value: 300,
    imageUrl: 'https://placehold.co/600x400/3ddc84/ffffff',
    instructions: `1. Open the Google Play Store app.\n2. Tap Menu > Redeem.\n3. Enter your code.\n4. Tap "Redeem".`,
    category: 'Gift Card',
  },
  {
    id: '15',
    platform: 'Google Play',
    name: 'Google Play Gift Code',
    value: 500,
    imageUrl: 'https://placehold.co/600x400/3ddc84/ffffff',
    instructions: `1. Open the Google Play Store app.\n2. Tap Menu > Redeem.\n3. Enter your code.\n4. Tap "Redeem".`,
    category: 'Gift Card',
  },
  
  // Netflix
  {
    id: '18',
    platform: 'Netflix',
    name: 'Mobile Plan',
    value: 149,
    imageUrl: 'https://placehold.co/600x400/e50914/ffffff',
    instructions: `1. Go to netflix.com/redeem.\n2. Enter the PIN code.`,
    category: 'Membership',
    planType: 'Monthly',
    features: ['Good video quality (480p)', 'Watch on your phone or tablet', 'Watch on 1 device at a time'],
  },
  {
    id: '9',
    platform: 'Netflix',
    name: 'Basic Plan',
    value: 199,
    imageUrl: 'https://placehold.co/600x400/e50914/ffffff',
    instructions: `1. Go to netflix.com/redeem.\n2. Enter the PIN code.`,
    category: 'Membership',
    planType: 'Monthly',
    features: ['Good video quality (720p)', 'Watch on your TV, computer, phone or tablet', 'Watch on 1 device at a time'],
  },
  {
    id: '11',
    platform: 'Netflix',
    name: 'Standard Plan',
    value: 499,
    imageUrl: 'https://placehold.co/600x400/e50914/ffffff',
    instructions: `1. Go to netflix.com/redeem.\n2. Enter the PIN code.`,
    category: 'Membership',
    planType: 'Monthly',
    features: ['Great video quality (1080p)', 'Watch on your TV, computer, phone or tablet', 'Watch on 2 devices at a time'],
    popular: true,
  },
  {
    id: '16',
    platform: 'Netflix',
    name: 'Premium Plan',
    value: 649,
    imageUrl: 'https://placehold.co/600x400/e50914/ffffff',
    instructions: `1. Go to netflix.com/redeem.\n2. Enter the PIN code.`,
    category: 'Membership',
    planType: 'Monthly',
    features: ['Best video quality (4K+HDR)', 'Watch on your TV, computer, phone or tablet', 'Watch on 4 devices at a time', 'Spatial audio included'],
  },

  // Spotify
  {
    id: '20',
    platform: 'Spotify',
    name: 'Student Plan',
    value: 59,
    imageUrl: 'https://placehold.co/600x400/1db954/000000',
    instructions: `1. Go to spotify.com/redeem.\n2. Log in or create your Spotify account.\n3. Enter the PIN.`,
    category: 'Membership',
    planType: 'Monthly',
    features: ['1 verified Premium account', 'Discount for eligible students', 'Ad-free music listening', 'Listen anywhere—even offline'],
  },
  {
    id: '10',
    platform: 'Spotify',
    name: 'Individual Plan',
    value: 119,
    imageUrl: 'https://placehold.co/600x400/1db954/000000',
    instructions: `1. Go to spotify.com/redeem.\n2. Log in or create your Spotify account.\n3. Enter the PIN.`,
    category: 'Membership',
    planType: 'Monthly',
    features: ['1 Premium account', 'Ad-free music listening', 'Listen anywhere—even offline', 'On-demand playback'],
    popular: true,
  },
  {
    id: '12',
    platform: 'Spotify',
    name: 'Duo Plan',
    value: 149,
    imageUrl: 'https://placehold.co/600x400/1db954/000000',
    instructions: `1. Go to spotify.com/redeem.\n2. Log in or create your Spotify account.\n3. Enter the PIN.`,
    category: 'Membership',
    planType: 'Monthly',
    features: ['2 Premium accounts', 'For couples who live together', 'Ad-free music listening', 'Listen anywhere—even offline', 'On-demand playback'],
  },
  {
    id: '17',
    platform: 'Spotify',
    name: 'Family Plan',
    value: 179,
    imageUrl: 'https://placehold.co/600x400/1db954/000000',
    instructions: `1. Go to spotify.com/redeem.\n2. Log in or create your Spotify account.\n3. Enter the PIN.`,
    category: 'Membership',
    planType: 'Monthly',
    features: ['Up to 6 Premium accounts', 'For family members living together', 'Block explicit music', 'Ad-free music listening', 'Listen anywhere—even offline'],
  },
  {
    id: '19',
    platform: 'Spotify',
    name: 'Individual Plan',
    value: 1189,
    imageUrl: 'https://placehold.co/600x400/1db954/000000',
    instructions: `1. Go to spotify.com/redeem.\n2. Log in or create your Spotify account.\n3. Enter the PIN.`,
    category: 'Membership',
    planType: 'Annual',
    features: ['1 Premium account', '12 months for a one-time payment', 'Ad-free music listening', 'Listen anywhere—even offline', 'On-demand playback'],
  },
];
